### ISSUE TITLE
Support for pulsarcentric flag in the header

### ISSUE THREAD

**Issue by devanshkv** [jayanthc/yapp#1]
yapp_viewdata segfaults when given filterbanks with pulsarcentric flag in their header.
```bash
WARNING: Unknown field label pulsarcentric encountered!
WARNING: Unknown field label  encountered!
Segmentation fault (core dumped)
```

**Comment by jayanthc** [comment]
@devanshkv: Thanks for bringing this up! I'll take a look at it. Is there a file with this flag that I can test with, on bowser, or one of the other WVU machines?

**Comment by devanshkv** [comment]
These are filterbanks written using `filterbank.py` from `PRESTO`.
You can find them `/hyrule/data/users/dagarwal/FLAG/S02/G75.00f/*.fil`

**Comment by jayanthc** [comment]
@devanshkv: I've fixed the issue. I've added support for the 'pulsarcentric' flag in filterbank headers. I've also modified the metadata-reading behaviour in the following way: If any unknown label is found in a filterbank file, YAPP will throw an error and exit gracefully instead of crashing. (Unfortunately, unknown labels cannot just be skipped because the data type that the label refers to is unknown, so exiting gracefully is the only option.) Please let me know if you find any other issue.
